In [26]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/TheTitanic.csv')

In [27]:
df.head(10)

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
2,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28,1,24,C,08-Jan-90

In [28]:
# Checking for duplicate vlaues
df.duplicated()
# Dropping the duplicate values and changing the dataset without re-assigning
df.drop_duplicates(inplace= True)

In [29]:
df.head(10)

,1,2,3,4,5,6,7,8,9,10
0,sn,pclass,survived,NaN,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20,0,7.925,S,09-Jan-90

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1301 entries, 0 to 1301
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1301 non-null   object
 1   2       1301 non-null   object
 2   3       1301 non-null   object
 3   4       1300 non-null   object
 4   5       1300 non-null   object
 5   6       1044 non-null   object
 6   7       1299 non-null   object
 7   8       1299 non-null   object
 8   9       1296 non-null   object
 9   10      1301 non-null   object
dtypes: object(10)
memory usage: 111.8+ KB

In [31]:
# We can see that the 4th column has no name (column 4, row 0). However, i tis understood that it has the names of the passenger, so we will change the value of the cell for ease
print(df.columns)

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='object')

In [32]:
#ColNames = {1: "Serial Number", 2: "Pclass", 3: "Survived", 4: "Name", 5:"Gender", 6:"Age", 7:"Family", 8:"Fare", 9:"Embarked", 10:"Date"}
ColNames = list(["Serial Number", "Pclass", "Survived", "Name", "Gender", "Age", "Family", "Fare", "Embarked", "Date"])
df.columns=ColNames

In [33]:
print(df.columns)

Index(['Serial Number', 'Pclass', 'Survived', 'Name', 'Gender', 'Age',
       'Family', 'Fare', 'Embarked', 'Date'],
      dtype='object')

In [34]:
#Removing the first row of the dataset since we have already name the columns as per our requirement
df = df.drop(0)

In [35]:
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,?,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18,0,7.2292,C,10-Jan-90

In [36]:
# We can see there are some missing values and special symbols in the age column. We need to fix these.

#Forcing the Age column to be string. So, we can manipulate it.
df['Age'] = df['Age'].astype(str) 

#Using Regular Expressions (regex) to strip out anything that isn’t a number or a decimal point.
df['Age'] = df['Age'].str.replace(r'[^\d\.]','', regex = True)

#Converting empty strings in Age column to true NaN values
df['Age'] = df['Age'].replace('', np.nan)

#Converting the column from string type tp foating type
df['Age'] = df['Age'].astype(float)

In [37]:
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,NaN,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2,**,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30.0,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,7.2292,C,10-Jan-90

In [38]:
#Cleaning the Gender column
# For row 4, the name contains "Mr.", so we can safely infer they are male!
df['Gender'] = df['Gender'].fillna(df['Name'].apply(lambda x: 'male' if 'Mr.' in str(x) or 'Master' in str(x) else 'female' if 'Mrs.' in str(x) or 'Miss' in str(x) else np.nan))

In [39]:
### On the Titanic, a first-class passenger was generally older than a third-class immigrant. You can fill the missing ages based on the median age of their specific Passenger Class (Pclass) and Gender.
# Filling NaNs with median age of matching Pclass and Gender groups
df['Age'] = df['Age'].fillna(df.groupby(['Pclass', 'Gender'])['Age'].transform('median'))

In [40]:
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,25.0,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",male,29.5,2,**,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30.0,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,7.2292,C,10-Jan-90

In [41]:
# Cleaning the Fare column
# We can see there are some special symbols (*) in the Fare column. We will replace them with true NaN values
import numpy as np
df['Fare'] = df['Fare'].replace(r'\*','',regex=True)
df['Fare'] = df['Fare'].replace('',np.nan,regex=True)

In [42]:
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,25.0,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",male,29.5,2,NaN,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30.0,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,7.2292,C,10-Jan-90

In [43]:
# Filling NaN values with median Fare value grouped by Pclass and Gender
df['Fare'] = df['Fare'].fillna(df.groupby(['Pclass','Gender'])['Age'].transform('median'))
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,NaN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,25.0,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",male,29.5,2,29.5,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30.0,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,7.2292,C,10-Jan-90

In [44]:
# Cleaning the Embarked column
# We can see that there are three values in the Embarked column - S, C, Q. However, there are some missing values. It is also possible that the values have spaces or are in lowercase. We need to fix these issues.

# Forcing the column to string type from object type so as to manipulate data as required
df['Embarked'] = df['Embarked'].astype(str)

# Stripping the string of left and right whitespaces
df['Embarked'] = df['Embarked'].str.strip()

# Converting all the values to uppercase
df['Embarked'] = df['Embarked'].str.upper()

# Replacing missing vlaues with true NaN values
df['Embarked'] = df['Embarked'].replace('',np.nan,regex=True)

In [45]:
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,NAN,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,25.0,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",male,29.5,2,29.5,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30.0,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,7.2292,C,10-Jan-90

In [46]:
# Explicitly replacing the string 'NAN' with a true Python NaN object
df['Embarked'] = df['Embarked'].replace('NAN', np.nan)
# Replacing NaN values with the most common value (the mode of the Embarked column)
modeEmbarked = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(modeEmbarked)
df.head(10)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,S,01-Jan-90
3,2,3,0,Master. Eugene Joseph,male,25.0,2,20.25,S,02-Jan-90
4,3,2,0,"Abbott, Mr. Rossmore Edward",male,29.5,2,29.5,S,03-Jan-90
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,04-Jan-90
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,05-Jan-90
7,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,7.65,S,06-Jan-90
8,7,2,0,"Abelson, Mr. Samuel",male,30.0,1,24,C,07-Jan-90
9,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,24,C,08-Jan-90
10,9,3,1,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,0,7.925,S,09-Jan-90
11,10,3,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,7.2292,C,10-Jan-90

In [47]:
# Cleaning the date column.
# We can see that there are "#######" strings at multiple places in the Date column.
# We will firstly replace them with true NaN values and then fill them with the most common date (mode of Date)
# We can also see that a format is being followed for the date, date-shortMonth- year, eg: 01-Jan-90

# Forcing the Date column to string type from onject type
df['Date'] = df['Date'].astype(str)

# Stripping the data of left and right whitespaces
df['Date'] = df['Date'].str.strip()

# Replacing # with empty strings
df['Date'] = df['Date'].replace(r'#', '', regex=False)

# Replacing empty values with true NaN values
df['Date'] = df['Date'].replace('', np.nan)

# Converting to date-time.
df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%y', errors = 'coerce')

# Handling the NaT values

# Finding the most common date (mode of Date)
mostCommonDate = df['Date'].mode()[0]

# Filling the missing dates with the most common date 
df['Date'] = df['Date'].fillna(mostCommonDate)

In [48]:
df.head(100)

,Serial Number,Pclass,Survived,Name,Gender,Age,Family,Fare,Embarked,Date
1,1,3,0,Mr. Anthony,male,42.0,0,7.55,S,1990-01-01
3,2,3,0,Master. Eugene Joseph,male,25.0,2,20.25,S,1990-01-02
4,3,2,0,"Abbott, Mr. Rossmore Edward",male,29.5,2,29.5,S,1990-01-03
5,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2,20.25,S,1990-01-04
6,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0,7.65,S,1990-01-05
...,...,...,...,...,...,...,...,...,...,...
97,96,3,0,"Barton, Mr. David John",male,22.0,0,8.05,S,1990-04-06
98,97,2,0,"Bateman, Rev. Robert James",male,51.0,0,12.525,S,1990-04-07
99,98,1,0,"Baumann, Mr. John D",male,42.0,0,25.925,S,1990-04-08
100,99,1,0,"Baxter, Mr. Quigg Edmond",male,24.0,1,247.5208,C,1990-04-09
101,100,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,1,247.5208,C,1990-04-10

In [49]:
df.to_csv('TheTitanicCleaned.csv', index=False)