### 1. Dropping irrelevant columns 
a. Serial Number  
b. Name  
c. Date

In [1]:
import pandas as pd 
df = pd.read_csv('TheTitanicCleaned.csv')
df = df.drop(columns=['Serial Number', 'Name', 'Date'])

y = df['Survived']

In [2]:
df.head(10)

   Pclass  Survived  Gender   Age  Family     Fare Embarked
0       3         0    male  42.0     0.0   7.5500        S
1       3         0    male  25.0     2.0  20.2500        S
2       2         0    male  29.5     2.0  29.5000        S
3       3         1  female  35.0     2.0  20.2500        S
4       3         1  female  16.0     0.0   7.6500        S
5       3         1    male  25.0     0.0   7.6500        S
6       2         0    male  30.0     1.0  24.0000        C
7       2         1  female  28.0     1.0  24.0000        C
8       3         1    male  20.0     0.0   7.9250        S
9       3         1  female  18.0     0.0   7.2292        C

### 2. Encoding categorical features into numbers
a. Gender   
b. Embarked

In [35]:
# Label encoding is good for binary data so we will use it for Gender encoding
# One Hot Encoding is good for categorical data with more than 2 categories
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
df['Gender'] = ohe.fit_transform(df[['Gender']])
df['Embarked'] = ohe.fit_transform(df[['Embarked']])
df.head(10)

   Pclass  Survived  Gender   Age  Family     Fare  Embarked
0       3         0     0.0  42.0     0.0   7.5500       0.0
1       3         0     0.0  25.0     2.0  20.2500       0.0
2       2         0     0.0  29.5     2.0  29.5000       0.0
3       3         1     1.0  35.0     2.0  20.2500       0.0
4       3         1     1.0  16.0     0.0   7.6500       0.0
5       3         1     0.0  25.0     0.0   7.6500       0.0
6       2         0     0.0  30.0     1.0  24.0000       1.0
7       2         1     1.0  28.0     1.0  24.0000       1.0
8       3         1     0.0  20.0     0.0   7.9250       0.0
9       3         1     1.0  18.0     0.0   7.2292       1.0

### 3. Feature Scaling
a. Age  
b. Fare  
Columns like Age (ranging from 0 to 80) and Fare (ranging from 0 to 512) live on completely different scales. Algorithms like Logistic Regression or Support Vector Machines can get warped by large numbers.

We can use StandardScaler to normalize these features so they share a common variance scale.

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Scale Age and Fare columns
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

In [37]:
df.head(10)

   Pclass  Survived  Gender       Age  Family      Fare  Embarked
0       3         0     0.0  0.958783     0.0 -0.499710       0.0
1       3         0     0.0 -0.329772     2.0 -0.254808       0.0
2       2         0     0.0  0.011316     2.0 -0.076435       0.0
3       3         1     1.0  0.428201     2.0 -0.254808       0.0
4       3         1     1.0 -1.011948     0.0 -0.497782       0.0
5       3         1     0.0 -0.329772     0.0 -0.497782       0.0
6       2         0     0.0  0.049215     1.0 -0.182495       1.0
7       2         1     1.0 -0.102380     1.0 -0.182495       1.0
8       3         1     0.0 -0.708759     0.0 -0.492479       0.0
9       3         1     1.0 -0.860353     0.0 -0.505896       1.0

### Splitting into Training and Testing sets

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)
# 20% of the data will be used for training the model
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")

Training features shape: (1040, 7)
Testing features shape: (260, 7)